# This file was generated by GoReleaser. DO NOT EDIT.
cask "intropy" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "741f0a62c4f4c0d678a834d7dbc23236337da4fb21e6caff03ff2238e4d60a04"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8dd16e6444e0b3106ee37fbe59858895e27babb840eb85f3543690e86ca748e"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "af2927d50212afdc6c83ec2964ea8862a5bb07b6ef3606018cb29b13576e0f8c"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec6a31781b4090ccbedb2311a45431f8e36c8d3faed73940ad882a615bf51b96"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "intropy"
  desc "CLI for Intropy integrations"
  homepage "https://github.com/integrio-intropy/intropy-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "intropy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/intropy"]
    end
  end
  generate_completions_from_executable "intropy", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
