# This file was generated by GoReleaser. DO NOT EDIT.
cask "intropy" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "b23540d9c5e8898cd56121834cec4313f2946310da6099fefe1a7e9393b60628"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80b20f9163fe8929160397de814a46f4ae7257a46bd30ee5512b4e1c91a09d70"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d585020bc04b0ab50ee3be2b1303ef02471ff552e44f760405dd60bb010f82d4"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4aa28217a5743c9aea13e531cd77fb01e650986118a105522551bc45be36b623"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "intropy"
  desc "CLI for Intropy integrations"
  homepage "https://github.com/integrio-intropy/intropy-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "intropy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/intropy"]
    end
  end
  generate_completions_from_executable "intropy", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
