# This file was generated by GoReleaser. DO NOT EDIT.
cask "intropy" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "1a3344672db29d71eec1a6314312e08e83cb9a756a2d641eaa283ffc32096bb4"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fc0506c077596d85c13dc1cba1b6c288ae5777cb7fbb1f61d48f453a2fa900f"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "708db5aed1d2cdf7d44f64a3f4d744e7a89c3662c6c605aa68da9c9af0cb164d"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd065482fd0975e2e3d959302c198f20c8144217adc50abc323ed67fbed36fc1"
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v#{version}/intropy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "intropy"
  desc "CLI for Intropy integrations"
  homepage "https://github.com/integrio-intropy/intropy-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "intropy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/intropy"]
    end
  end
  generate_completions_from_executable "intropy", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
