# frozen_string_literal: true

# This file was generated by the intropy release workflow. DO NOT EDIT.
class Intropy < Formula
  desc "CLI for Intropy integrations"
  homepage "https://github.com/integrio-intropy/intropy-cli"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v0.10.0/intropy_0.10.0_darwin_amd64.tar.gz"
      sha256 "654eb0c64843e1eff19683dbea27b5b891c8fec31838e67af0ed92a88e8d39cc"
    end

    if Hardware::CPU.arm?
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v0.10.0/intropy_0.10.0_darwin_arm64.tar.gz"
      sha256 "931e74b600633fb396ae7b5955ea1852b2f18d3f05e821bd1c47fd85664a1d30"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v0.10.0/intropy_0.10.0_linux_amd64.tar.gz"
      sha256 "727bbcdcf37234950bbed48ac77c37cbd0a469755b392a177ba086f83bdda96e"
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/integrio-intropy/intropy-cli/releases/download/v0.10.0/intropy_0.10.0_linux_arm64.tar.gz"
      sha256 "b24f3bcf9c9913a1c842306193e3b615c07c624919530fdb3b735091dddde644"
    end
  end

  def install
    bin.install "intropy"
    generate_completions_from_executable(bin/"intropy", "completion")
  end

  test do
    system "#{bin}/intropy", "version"
  end
end
